### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by steroal** [ErbB4/erbb4.github.io#6]
你好 我叫罗疏桐 上海海洋大学的研一新生  课题计算神经科学这块的模拟 在nestml的issues中看到了你的提问 请问你解决了吗 就是那个make报错的问题
很高兴认识你

**Comment by ErbB4** [comment]
你好，你试试 mac 吧。因为 Linux 官方还没有 nest3.0

或者你试试 docker.

我装了还没用。

很高兴认识你。我是卢晗。

**Comment by steroal** [comment]
谢谢  
但是我没mac  (´;ω;)
换一个模拟器用了只能

**Comment by steroal** [comment]
have  a good day
